### ISSUE TITLE
Migrate to MySQL 8

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#101]
For no particular reason at all, our database is MySQL 5.7 and 8 is a bigger number so let's try to switch to it.

**Comment by metalcanine** [comment]
8 is like, 3 better at least.
Also tests are running in CI in 8.0.19 and I've been successfully running tests locally in 8.0.22 with no problems

**Comment by bayounetta** [comment]
With changes in #282 tests in CI are still being run in MySQL 8

**Comment by tomrittervg** [comment]
This seems fine.
