### ISSUE TITLE
Output the revision updatebot is running on in the logs.

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#115]
Right before [this line](https://github.com/mozilla-services/updatebot/blob/master/automation.py#L136) we should do [this](https://github.com/mozilla-services/updatebot/blob/master/components/logging.py#L96-L97) (except using the commandrunner) and output the revision at Info level.

**Comment by metalcanine** [comment]
Re-opened due to unexpected CI failures
