### ISSUE TITLE
Use debug-level logging in Taskcluster

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#117]
Add an elif [right here](https://github.com/mozilla-services/updatebot/blob/9949ae5f677dd4caa7e74adfdb9825125227fb3a/components/logging.py#L84) that [checks this](https://github.com/mozilla-services/updatebot/blob/9949ae5f677dd4caa7e74adfdb9825125227fb3a/components/logging.py#L115) and makes the default level Debug.

**Comment by metalcanine** [comment]
This should have been auto-closed but wasn't, closing it now!
