### ISSUE TITLE
Everyone should Get a Google Cloud account

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#12]
https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=SVCOPS&title=Google+Cloud+Platform+%28GCP%29+For+Firefox+Organization

**Comment by metalcanine** [comment]
- [ ] tritter ([Bug 1622834](https://bugzilla.mozilla.org/show_bug.cgi?id=1622834))
- [ ] freddy (No bug yet)
- [ ] jewilde (No bug yet)

**Comment by tomrittervg** [comment]
You should both have access to the dev database (there is no prod database yet.)
