### ISSUE TITLE
Intermittent error when running jq in CI

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#154]
`/bin/bash: line 6: /usr/bin/jq: Argument list too long` sometimes crops up usually accompanied by test errors that go unreported due to the jq error.

Solving for #130 may make this easier to diagnose and fix

**Comment by tomrittervg** [comment]
I'm going to guess this is a problem happening before jq that's munging the data we expect to pass to jq.  If jq fails I would just take the raw data and send it over to pr_comment...

**Comment by tomrittervg** [comment]
This was happening because the output from the previous command was too long for a command-line argument.
