### ISSUE TITLE
Implement the database function calls in automation that don't exist

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#17]
https://github.com/mozilla-services/third-party-library-update/blob/3806318819c2bd084173fb637d7bc1151a25d73f/automation.py#L27

For Hardcoded Database, they're just going to do nothing... (ellipsis emphasis Tom's)

**Comment by tomrittervg** [comment]
I've started this.

**Comment by tomrittervg** [comment]
Pushed some work on this.
