### ISSUE TITLE
./mach vendor behaved differently in CI than locally

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#176]
When run in CI [this update failed](https://bugzilla.mozilla.org/show_bug.cgi?id=1707051) but when I ran it locally it succeeded?

**Comment by tomrittervg** [comment]
This is  because Updatebot in m-c is running on Python 3.5 which doesn't have an API I need.

I got it working here: https://bugzilla-dev.allizom.org/show_bug.cgi?id=1630433

Need to fix up my patches though and figure out how to get python 3.8 in the image safely.

**Comment by tomrittervg** [comment]
Nope, doing this: https://bugzilla.mozilla.org/show_bug.cgi?id=1709401

**Comment by metalcanine** [comment]
Should we also open a bug here on github for moving the poetry requirements backwards to python 3.5?

**Comment by metalcanine** [comment]
Specifically moving from `python = "^3.5"` to `python = "3.5"` in the pyproject.toml

**Comment by tomrittervg** [comment]
Probably? You tell me :)
