### ISSUE TITLE
Switch updatebot to actually poke maintainers, not me

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#179]

**Comment by tomrittervg** [comment]
Actually, it is correctly needinfo-ing the maintainer (it needinfos me on libdav1d because I'm marked as the maintainer.)

It's not correctly assigning the bug though.

**Comment by saschanaz** [comment]
I didn't get an NI though, did I do something wrong in libjxl settings? 🤔

**Comment by tomrittervg** [comment]
No; that's expected.  We just need to set the assignee [here](https://github.com/mozilla-services/updatebot/blob/3738d784bfb65c0c027059634e31e1e2444f6541/tasktypes/vendoring.py#L377) also.
