### ISSUE TITLE
Figure out needinfo/flag for review for the libraries 

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#18]
Figure out how we're going to figure out who to needinfo/flag for review for the libraries

Can this be determined from moz.build files?
Or do we need to hardcode it in the database?

**Comment by tomrittervg** [comment]
Current thinking is once #48 is done, we'll put this information in the moz.yaml

**Comment by tomrittervg** [comment]
And since #48 isn't in the MVP, in the meantime we'll put it in the libraries table.
