### ISSUE TITLE
Attach the phabricator patch.

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#20]
There's stuff that does this already in-tree, so there's something to vaguely copy or look at for reference.

https://searchfox.org/mozilla-central/source/taskcluster/docker/python-dependency-update/runme.sh

**Comment by tomrittervg** [comment]
I did a little bit of this: added arcanist to the Dockerfile and retrieved the phabricator token (which doesn't exist yet) from taskclsuter secret.

**Comment by tomrittervg** [comment]
Done.
