### ISSUE TITLE
be more explicit about reviewing commits from updatebot

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla-services/updatebot#257]
Someone made the point that we should be more explicit when providing a patch for review:
We are basically throwing untrusted paches over the fence and the try-run only talks about compatibility/stability, but not trustworthiness/functionality/security.

It seems it would be good to make an explicit statement that regardless of the "try" results, a careful review is still required.

Given this is a review-specific commit, I wonder if it would make sense to not just have a commit title but a longer body with some boilerplate text? 🤔 
If so, the code we'd want to touch is at https://github.com/mozilla-services/updatebot/blob/c73d19b07bd2c3beed530b6a11f5417c83932e74/components/hg.py#L18

**Comment by tomrittervg** [comment]
I don't think we should be putting boilerplate instructions to reviewers in our commit messages - that's going to be in our repo forever.  I think we should either be putting instructions in bugzilla or phabricator comments.  Making a bugzilla comment is trivial (all our comment templates [are here](https://github.com/mozilla-services/updatebot/blob/master/components/bugzilla.py)), making a phabricator comment isn't currently supported, but we could do that if you want.

Can you suggest text and where/when to put it?

**Comment by mozfreddyb** [comment]
Well, that's a very good point. It's just a bit annoying that people will review in phabricator and the comment is in bugzilla. But so it is.

Is this `UPDATE_DETAILS` from https://github.com/mozilla-services/updatebot/blob/c73d19b07bd2c3beed530b6a11f5417c83932e74/components/bugzilla.py#L26-L30?

**Comment by tomrittervg** [comment]
We can do a phabricator comment, it's just not a one-line-change :)

The Bugzilla comments would be DONE_CLASSIFIED_FAILURE, DONE_UNCLASSIFIED_FAILURE, and DONE_ALL_SUCCESS - those are when we flag a revision for review.

**Comment by mozfreddyb** [comment]
Let's start with a bugzilla comment
