### ISSUE TITLE
Rename the github repo to 'updatebot'

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#3]
Also [update the holly job](https://hg.mozilla.org/projects/holly/diff/bb8213d30c2a209facb5d459a00c8e683599e062/taskcluster/docker/updatebot/run.py#l1.51)

**Comment by metalcanine** [comment]
This is done

**Comment by tomrittervg** [comment]
You also have to update the script in holly.

**Comment by metalcanine** [comment]
Thanks! Sorry, I'll fix this tomorrow

**Comment by metalcanine** [comment]
[Actually done this time!](https://hg.mozilla.org/projects/holly/rev/9a7ee164217e035f22f732330962868c61e8d897)
