### ISSUE TITLE
Implement ./mach vendor --check-for-update

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#5]
This returns nothing if the library is up to date, or the new version identifier (commit hash probably) if there is a new version.

We're going to rewrite most of ./mach vendor, so this is primarily a stopgap/testing exercise. Implement it for [dav1d](https://searchfox.org/mozilla-central/source/python/mozbuild/mozbuild/mach_commands.py#1349-1361) by adding a new CommandArgument, and then [figure out if the new version is different from the current version, and return it if so](https://searchfox.org/mozilla-central/source/python/mozbuild/mozbuild/vendor_dav1d.py#154-155).

**Comment by tomrittervg** [comment]
I looked at this a little bit, and this is pretty complicated. I started a thread in #secinf with glob for input.
