### ISSUE TITLE
For a library, file all update bugs under a single meta bug for that library.

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#57]
We can specify that meta bug number in the udatebot configuration once #48 is done.

**Comment by baumanj** [comment]
I see that https://github.com/mozilla-services/updatebot/issues/48 is done. Is this feature available? I looked a bit, but couldn't find any indication about where in a moz.yaml the metabug would be specified.

**Comment by tomrittervg** [comment]
This was done https://bugzilla.mozilla.org/show_bug.cgi?id=1770895 and https://github.com/mozilla-services/updatebot/pull/246
