### ISSUE TITLE
Update run_command to catch the timeout exception

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#7]
https://github.com/mozilla-services/third-party-library-update/blob/3806318819c2bd084173fb637d7bc1151a25d73f/components/utilities.py#L22-L42

Also grab the output per [this](https://stackoverflow.com/questions/60675828/) and then output it and raise an Exception to be handled at the per-library-level.

**Comment by metalcanine** [comment]
https://github.com/mozilla-services/third-party-library-update/blob/master/automation.py#L16-L20

**Comment by tomrittervg** [comment]
Actually, I didn't fix `raise an Exception to be handled at the per-library-level.`

**Comment by tomrittervg** [comment]
This is done
