### ISSUE TITLE
Build on Linux only first, then expand to other platforms

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#85]
If a library revision causes a build failure; we've wasted a bunch of resources to find out that it fails on every platform. (That could be guessed in most cases.)  It would be better to build on Linux first and after that build succeeds, add the rest of the platforms.

(Specifically I'm saying the build job; if the tests fail on Linux I think we would still want to at least build on all other platforms as there are often platform-specific files/build configurations.)

(Child of #83)

**Comment by tomrittervg** [comment]
This is now blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1678777 

I may be able to make some progress on it if I run a couple of separate try runs though...

**Comment by tomrittervg** [comment]
This is currently a WIP in the issue-85 branch

**Comment by tomrittervg** [comment]
The try runs for this are
 - https://treeherder.mozilla.org/jobs?repo=try&revision=fa34db961043c78c150bef6b03d7426501aabd8b
 - https://treeherder.mozilla.org/jobs?repo=try&revision=3fe6e60f4126d7a9737480f17d1e3e8da384ca75

**Comment by tomrittervg** [comment]
I've pushed an update to the issue-85 branch that has this mostly done. The remaining bits are to cut across the remaining functionality tests.

**Comment by metalcanine** [comment]
Solved with most recent pr merges! (#113) 🎉
