### ISSUE TITLE
Update run_command to raise an Exception if we don't return correctly

### ISSUE THREAD

**Issue by metalcanine** [mozilla-services/updatebot#9]
to be handled at the per-library-level

https://github.com/mozilla-services/third-party-library-update/blob/3806318819c2bd084173fb637d7bc1151a25d73f/components/utilities.py#L22-L42

https://github.com/mozilla-services/third-party-library-update/blob/3806318819c2bd084173fb637d7bc1151a25d73f/components/utilities.py#L35-L41

https://github.com/mozilla-services/third-party-library-update/blob/3806318819c2bd084173fb637d7bc1151a25d73f/automation.py#L16-L20

**Comment by tomrittervg** [comment]
This is done.
