### ISSUE TITLE
Improve intermittent classifications

### ISSUE THREAD

**Issue by tomrittervg** [mozilla-services/updatebot#90]
In [this sample try run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=5b0969e6246b2e70eb3af003501ab69c066cbfcc&selectedTaskRun=Vf6_lg7KRpua9JJu5OyZCg.0) we upgraded libdav1d and got some test failures. None of them were classified as an intermittent or other bug.

However, many of them were in fact known intermittents.  We should do better at surfacing this to developers.

**Comment by metalcanine** [comment]
closed by #92
